// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkfe7j9c6yXkTI-5mSy6i4nkj4tJNmQdA',
    appId: '1:580172959026:web:511dbe52e33cbc248c9b2b',
    messagingSenderId: '580172959026',
    projectId: 'plant-care-8a962',
    authDomain: 'plant-care-8a962.firebaseapp.com',
    storageBucket: 'plant-care-8a962.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGJyXURngDKCX-mRZSICenyMk25wOSLGs',
    appId: '1:580172959026:android:193b2d835f5ea3008c9b2b',
    messagingSenderId: '580172959026',
    projectId: 'plant-care-8a962',
    storageBucket: 'plant-care-8a962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcorYiO-gEi5XOsjQ8CI0kZ0A5gkqc9ck',
    appId: '1:580172959026:ios:f8be2eed22e139758c9b2b',
    messagingSenderId: '580172959026',
    projectId: 'plant-care-8a962',
    storageBucket: 'plant-care-8a962.firebasestorage.app',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcorYiO-gEi5XOsjQ8CI0kZ0A5gkqc9ck',
    appId: '1:580172959026:ios:f8be2eed22e139758c9b2b',
    messagingSenderId: '580172959026',
    projectId: 'plant-care-8a962',
    storageBucket: 'plant-care-8a962.firebasestorage.app',
    iosBundleId: 'com.example.plantCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkfe7j9c6yXkTI-5mSy6i4nkj4tJNmQdA',
    appId: '1:580172959026:web:cf5884272da447508c9b2b',
    messagingSenderId: '580172959026',
    projectId: 'plant-care-8a962',
    authDomain: 'plant-care-8a962.firebaseapp.com',
    storageBucket: 'plant-care-8a962.firebasestorage.app',
  );
}
